### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by NextrPlue** [PNU-BE-3Team/fizzbuzz#1]
fizzbuzz 알고리즘을 구현해야 합니다.

- [x] get 'n' to repeat (문성민)
- [x] print fizz (진서현)
- [x] print buzz (문성재)
- [x] print fizzbuzz (정재빈)
